In [2]:
import numpy as np 
import torch
a = np.array([1, 2, 3])                    # shape: (3,)
b = np.array([[1, 2], [3, 4], [5, 6]])     # shape: (3, 2)
c = np.zeros((2, 3, 4))                     # shape: (2, 3, 4)
d = np.ones((5, 1, 3, 8))                   # shape: (5, 1, 3, 8)

In [ ]:
# E0.1
x = np.arange(24).reshape(2,3,4)
# What is x.shape? (2,3,4)
# What is x[0].shape? (3,4)
# What is x[0, 1].shape? (4,)
# What is x[0, 1, 2].shape?  (scalar)


In [ ]:
# E0.2
x = torch.randn(8, 10, 512)
# What is x.shape?(8,10,512)
# What is x[0].shape? (10,512)
# What is x[:, 0, :].shape? (8,512)
# What is x[:, :, 0].shape? (8,10)

In [ ]:
k =torch.randn(2,3,4)
k

In [ ]:
k[:,0,:]

In [ ]:
# E0.3
x = np.zeros((4, 1, 3))
# What is x.shape? (4,1,3)
# What is x[0].shape? (1,3)
# What is x[0, 0].shape? (3,)

In [ ]:
# E0.4 — Real ML shapes. What does each dim likely represent?
embeddings = torch.randn(32, 128, 768)    # (32,128,768)
attention   = torch.randn(32, 8, 128, 128) # (32, 8, 128, 128)
conv_feat   = torch.randn(16, 64, 32, 32)  # (16, 64, 32, 32)

In [ ]:
x = np.array([[1, 2, 3],
              [4, 5, 6]])        # shape (2, 3)

x.sum(axis=1)                    # shape (2,)    — dim removed
# x.sum(axis=1, keepdims=True)     # shape (2, 1)  — dim kept as 1

axis and dimentions reasoning 

In [ ]:
# E1.1 — Predict output shape for each
x = np.ones((8, 10, 512))
# x.sum(axis=0).shape = ? (10,512)
# x.sum(axis=1).shape = ? (8,512)
# x.sum(axis=2).shape = ? (8,10)
# x.sum(axis=(0, 1)).shape = ? (512,)
# x.sum(axis=-1).shape = ? (8,10)
# x.max(axis=1).shape = ? (8,512) (note: np.max vs torch.max differ!)

In [ ]:
# E1.2 — Predict shapes
x = np.ones((32, 8, 128, 128))
# x.mean(axis=-1).shape = ? (32,8,128)
# x.mean(axis=-1, keepdims=True).shape = ? (32,8,128,1)
# x.sum(axis=(2, 3)).shape = ? (32,8)

In [ ]:
# E1.3 — Which axis to reduce?
# Given scores of shape (batch, heads, seq_len, seq_len) = (32, 8, 128, 128)
# To get attention weights, you softmax over the last dim (keys).
# What axis do you pass to softmax? Answer: axis=-1

In [ ]:
# E1.4 — Normalize each feature across the batch
x = np.random.randn(100, 5)  # 100 samples, 5 features
# Write code to compute:
#   mean per feature (shape should be (5,) or (1,5))
#   std per feature
#   z-scored x (each feature has mean≈0, std≈1)
x_mean = x.mean(axis=0, keepdims=True)
x_std = x.std(axis=0, keepdims=True)
z = (x-x_mean)/x_std


In [ ]:
# E1.5 — Real scenario: layer normalization
x = np.random.randn(2, 3, 4)  # (batch, seq, features)
# LayerNorm normalizes across the LAST dimension (features).
# Compute mean and std across dim=-1 with keepdims, then normalize.


def LayerNormed(x):
    x_mean = x.mean(axis=-1, keepdims=True)
    x_std = x.std(axis=-1, keepdims=True)
    return (x - x_mean) / x_std
LayerNormed(x)

In [ ]:
# E1.6 — argmax reasoning
x = np.array([[0.1, 0.7, 0.2],
              [0.3, 0.9, 0.4],
              [0.9, 0.05, 0.05]])
# x.argmax(axis=0) = ?  shape -> (3,) [2,1,1]
# x.argmax(axis=1) = ?  shape -> (3,) [1,1,0]

In [ ]:
# E2.1 — Implement ReLU without any loops or if statements
def relu(x):
    np.maximum(x,0)

In [ ]:

# E2.2 — Implement softmax along axis=-1 (no loops)
# softmax(x)_i = exp(x_i) / sum(exp(x_j))
# Hint: use keepdims
def softmax(x, axis=-1):
    x_exp = np.exp(x)
    return x_exp / x_exp.sum(axis=axis, keepdims=True)

In [ ]:
# E2.3 — Implement cross-entropy loss (no loops)
# L = -sum(y_true * log(y_pred)) / N
# y_true: (N, C) one-hot, y_pred: (N, C) probabilities
def cross_entropy(y_true, y_pred):
    N = y_true.shape[0]
    return -(y_true * np.log(np.clip(y_pred, 1e-9, 1))).sum() / N

In [ ]:
# E2.4 — Predict the output
a = np.array([[1, 2], [3, 4]])
b = np.array([[10, 20], [30, 40]])
# a * b = ? (2,2)
# a ** b = ?  (element-wise power) (2,2)
# np.maximum(a, 3) = ? (2,2)


In [ ]:

# E2.5 — GELU activation (approximate version)
# GELU(x) ≈ 0.5 * x * (1 + tanh(sqrt(2/π) * (x + 0.044715 * x^3)))
# Implement without loops:
def gelu(x):
    return 0.5 * x * (1 + np.tanh(np.sqrt(2 / np.pi) * (x + 0.044715 * x**3)))

In [ ]:
# E2.6 — Given logits of shape (batch, num_classes) = (4, 5):
logits = np.random.randn(4, 5)
# Compute softmax probabilities (should sum to 1 along axis=1)
# Verify: probs.sum(axis=1) should be [1, 1, 1, 1]
probs = softmax(logits, axis=1)
probs.sum(axis=1)

In [ ]:
# E3.1 — Predict the output shape
x = np.arange(24)
# x.reshape(2, 3, 4).shape = ? (2,3,4)
# x.reshape(6, -1).shape = ? (6,4)
# x.reshape(-1, 2, 3).shape = ? (4,2,3)
# x.reshape(2, 3, 4).reshape(-1).shape = ? (24,)

In [ ]:
# E3.2 — Predict values
x = np.arange(6).reshape(2, 3)
# x = ?  (write out the array) [[0,1,2],[3,4,5]]
# x.T = ? 
# [[0, 3],
# [1, 4],
# [2, 5]]
# x.reshape(3, 2) = ?       ← NOTE: this is NOT the same as x.T!
# Why are x.T and x.reshape(3,2) different?
# [[0, 1],
# [2, 3],
# [4, 5]]

In [ ]:
# E3.3 — Multi-head attention reshape
# Given Q of shape (batch=2, seq=4, d_model=6)
# with num_heads=2, head_dim=3
# Reshape Q to (batch, num_heads, seq, head_dim) = (2, 2, 4, 3)
Q = torch.arange(48, dtype=torch.float).reshape(2, 4, 6)
# Write the reshape + permute:
# Q_heads = ? Q.reshape(2,2,4,3).permute(0,2,1,3)

In [ ]:
# E3.4 — Undo the multi-head reshape
# Given Q_heads of shape (batch=2, num_heads=2, seq=4, head_dim=3)
# Reshape back to (batch=2, seq=4, d_model=6)
# Q_back = ?
# Verify: torch.equal(Q, Q_back)

In [9]:
Q = torch.arange(48, dtype=torch.float).reshape(2, 4, 6) # B, S, D_model
Q_reshape = Q.reshape(2,2,4,3).permute(0,2,1,3) #B, numh,seq,head_dim

Q_heads = Q.unflatten(-1, (2, 3)).transpose(1, 2)   # (B, H, S, hd)
Q_back  = Q_heads.transpose(1, 2).flatten(-2)       # (B, S, d_model)
torch.equal(Q, Q_back)  # True, and semantically correct

True

In [ ]:
# E3.5 — Add a batch dimension
x = torch.randn(10, 512)    # (seq_len, d_model) — single sequence
# Add batch dim to get (1, 10, 512)
# Method 1: unsqueeze
# Method 2: reshape
# Method 3: indexing with None

In [10]:
x = torch.randn(10, 512)
x.unsqueeze(0).shape

torch.Size([1, 10, 512])

In [12]:
x = torch.randn(10, 512)
x.reshape(1,10,512).shape

torch.Size([1, 10, 512])

In [ ]:
# E3.6 — Image format conversion
img = np.random.randint(0, 255, (224, 224, 3))  # HWC format
# Convert to CHW format: (3, 224, 224)
# img_chw = ?

In [15]:
img = np.random.randint(0, 255, (224, 224, 3))
img_chw = img.transpose(2, 0, 1)
img_chw.shape

(3, 224, 224)

In [ ]:
# E4.1 — Will these broadcast? If yes, what's the result shape?
# a: (5, 3) + b: (3,)         → ? yes (5,3)
# a: (5, 3) + b: (5,)         → ? No 
# a: (5, 3) + b: (1, 3)       → ? Yes (5,3)
# a: (5, 3) + b: (5, 1)       → ? Yes (5,3) 
# a: (2, 3, 4) + b: (3, 4)    → ?  Yes (2,3,4)
# a: (2, 3, 4) + b: (3, 1)    → ? yes (2,3,4)
# a: (2, 3, 4) + b: (2, 1, 1) → ? yes (2,3,4)
# a: (2, 3, 4) + b: (5, 3, 4) → ? No 
# a: (8, 1, 6, 1) + b: (7, 1, 5) → ? yes (8,7,6,5)

In [6]:
# E4.2 — Compute the outer product of two vectors WITHOUT loops
a = np.array([1, 2, 3, 4])    # (4,)
b = np.array([10, 20, 30])    # (3,)
# Result should be shape (4, 3) where result[i,j] = a[i] * b[j]
# outer = ?
outer  = a[:, np.newaxis] * b
outer.shape

(4, 3)

In [8]:
# E4.3 — Pairwise Euclidean distance matrix
# Given two sets of points:
A = np.random.randn(100, 3)   # 100 points in 3D
B = np.random.randn(50, 3)    # 50 points in 3D
# Compute distance matrix D of shape (100, 50)
# where D[i,j] = ||A[i] - B[j]||
# Hint: reshape A to (100, 1, 3) and B to (1, 50, 3)
# D = ?
A = A.reshape(100,1,3)
B = B.reshape(1,50,3)
D = np.sqrt((A - B)**2).sum(axis=2)
D.shape

(100, 50)

In [10]:
# E4.4 — Normalize each row to sum to 1 (without loops)
x = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]], dtype=float)
x_normalized = x / x.sum(axis=1, keepdims=True)
# Verify: x_normalized.sum(axis=1) should be [1, 1, 1]
x_normalized

array([[0.16666667, 0.33333333, 0.5       ],
       [0.26666667, 0.33333333, 0.4       ],
       [0.29166667, 0.33333333, 0.375     ]])

In [17]:
# E4.5 — Causal mask for attention
# Create a mask where mask[i,j] = 0 if j <= i, else -inf
# For seq_len = 4:
# [[ 0, -inf, -inf, -inf],
#  [ 0,    0, -inf, -inf],
#  [ 0,    0,    0, -inf],
#  [ 0,    0,    0,    0]]
seq_len = 4
mask = np.where(np.triu(np.ones((seq_len, seq_len), dtype=bool), k=1), -np.inf, 0.0)
mask

array([[  0., -inf, -inf, -inf],
       [  0.,   0., -inf, -inf],
       [  0.,   0.,   0., -inf],
       [  0.,   0.,   0.,   0.]])

In [18]:
# E4.6 — Temperature scaling
# Given logits of shape (batch, vocab_size) = (4, 1000)
# and temperature T (scalar), compute logits / T
# Then apply softmax along axis=-1
logits = np.random.randn(4, 1000)
T = 0.7
scaled_probs = logits/T 
def softmax(x):
    e_x = np.exp(x-np.max(x))
    return e_x/e_x.sum(axis=-1, keepdims=True)
scaled_probs = softmax(scaled_probs)
scaled_probs

array([[3.04594822e-04, 8.75854579e-04, 1.16401117e-03, ...,
        1.79733935e-04, 1.03916615e-04, 1.69822773e-03],
       [1.98885280e-04, 2.19003969e-04, 1.10391124e-04, ...,
        1.07298945e-03, 7.59668624e-05, 7.99818944e-04],
       [4.62686856e-03, 2.09213269e-03, 1.42735659e-03, ...,
        6.34643814e-04, 5.55445319e-04, 6.83707413e-04],
       [9.07565546e-04, 7.73607017e-05, 4.75518564e-04, ...,
        1.88061116e-03, 4.96497239e-04, 1.62290262e-03]], shape=(4, 1000))

In [20]:
# E4.7 — Batch-wise weighted sum
# weights: (batch, 3)    — 3 weights per sample
# values:  (batch, 3, dim) — 3 vectors per sample, each of dimension dim
# Goal: weighted sum → (batch, dim)
# result[b, d] = sum_i weights[b, i] * values[b, i, d]
weights = np.random.randn(4, 3)
values = np.random.randn(4, 3, 8)
# Hint: unsqueeze weights to (4, 3, 1), multiply, sum over axis=1
result = (weights[:, :, np.newaxis] * values).sum(axis=1)
result

array([[-1.38363493e+00, -1.65557191e+00,  1.53450765e+00,
         2.77930618e+00, -9.01528713e-01, -1.02464074e+00,
         2.85873244e+00, -7.87264280e-01],
       [-1.81179060e+00,  2.95472857e+00, -3.12985552e+00,
        -1.73911614e-01, -4.02795707e-01,  5.89473228e-01,
        -3.18166971e-01, -1.33133166e+00],
       [ 1.05130532e+00,  7.89486308e-01, -9.14463433e-01,
         4.23944613e+00,  1.89299407e+00,  2.54386561e+00,
        -3.54440444e-03, -1.54437260e+00],
       [-1.30389440e+00,  9.69856224e-01,  9.71734870e-01,
         6.88748458e-01, -7.25820144e-01,  7.56873130e-01,
        -1.13445856e+00,  6.86752234e-01]])

In [ ]:
import numpy as np
# E4.8 — Predict the output (compute by hand)
a = np.array([[1], [2], [3]])    # (3, 1)
b = np.array([[10, 20, 30]])     # (1, 3)
# a + b = ? (3,3)
# a * b = ? (3,3)
# a - b = ? (3,3)

In [7]:
# E5.1 — Implement logsumexp without loops
# logsumexp(x, axis) = log(sum(exp(x), axis))
# But numerically stable version:
# logsumexp(x) = max(x) + log(sum(exp(x - max(x))))
def logsumexp(x, axis=-1, keepdims=False):
    m = x.max(axis=axis, keepdims=True)
    out = m + np.log(np.exp(x - m).sum(axis=axis, keepdims=True))
    return out if keepdims else out.squeeze(axis)

In [ ]:
# E5.2 — Predict output (by hand)
x = np.array([[3, 1, 4],
              [1, 5, 9],
              [2, 6, 5]])
# x.max(axis=0) = ? [3,9,6]
# x.argmax(axis=0) = ?
# x.max(axis=1) = ? [4,9,6]
# x.argmax(axis=1) = ?
# x.sum(axis=0) - x.sum(axis=1) = ? [6,12,18] - [8,15,13] = [-2,-3,5]


In [15]:
import torch
# E5.3 — Top-k selection
x = torch.randn(4, 1000)   # (batch, vocab)
# Get top-5 values and indices per sample
# top_vals, top_idx = ?
top_vals = torch.topk(x, k=5, dim=-1).values
top_idx  = torch.topk(x, k=5, dim=-1).indices

In [19]:
# E5.4 — Boolean reductions
x = np.array([[1, -2, 3], [-4, 5, -6]])
# How many positive elements total?
# How many positive elements per row?
# Are ALL elements in row 0 positive?
# Is ANY element in row 1 positive?
positive_count = np.sum(x > 0)
positive_count_row = np.sum(x > 0, axis=1)
print(positive_count)
print(positive_count_row)

3
[2 1]


In [ ]:
# E5.5 — Variance from scratch (no np.var)
x = np.random.randn(100, 5)
# Compute variance of each feature (axis=0)
# var = mean((x - mean)^2)
# my_var = ?
# Verify: np.allclose(my_var, x.var(axis=0))

