In [2]:
import numpy as np 
import torch
a = np.array([1, 2, 3])                    # shape: (3,)
b = np.array([[1, 2], [3, 4], [5, 6]])     # shape: (3, 2)
c = np.zeros((2, 3, 4))                     # shape: (2, 3, 4)
d = np.ones((5, 1, 3, 8))                   # shape: (5, 1, 3, 8)

In [3]:
# E0.1
x = np.arange(24).reshape(2,3,4)
# What is x.shape? (2,3,4)
# What is x[0].shape? (3,4)
# What is x[0, 1].shape? (4,)
# What is x[0, 1, 2].shape?  (scalar)


In [ ]:
# E0.2
x = torch.randn(8, 10, 512)
# What is x.shape?(8,10,512)
# What is x[0].shape? (10,512)
# What is x[:, 0, :].shape? (8,512)
# What is x[:, :, 0].shape? (8,10)

In [11]:
k =torch.randn(2,3,4)
k

tensor([[[-0.1877, -0.4584,  1.2684, -0.0142],
         [ 1.0593, -1.2265, -0.9042,  0.4987],
         [-0.6269, -0.9685,  0.5445,  0.2106]],

        [[ 1.5403, -1.0171, -1.4491, -0.5357],
         [-0.3114,  1.0720,  0.1885, -0.7140],
         [-0.8081, -0.7156,  0.0849,  1.5459]]])

In [12]:
k[:,0,:]

tensor([[-0.1877, -0.4584,  1.2684, -0.0142],
        [ 1.5403, -1.0171, -1.4491, -0.5357]])

In [14]:
# E0.3
x = np.zeros((4, 1, 3))
# What is x.shape? (4,1,3)
# What is x[0].shape? (1,3)
# What is x[0, 0].shape? (3,)

In [ ]:
# E0.4 — Real ML shapes. What does each dim likely represent?
embeddings = torch.randn(32, 128, 768)    # (32,128,768)
attention   = torch.randn(32, 8, 128, 128) # (32, 8, 128, 128)
conv_feat   = torch.randn(16, 64, 32, 32)  # (16, 64, 32, 32)

In [26]:
x = np.array([[1, 2, 3],
              [4, 5, 6]])        # shape (2, 3)

x.sum(axis=1)                    # shape (2,)    — dim removed
# x.sum(axis=1, keepdims=True)     # shape (2, 1)  — dim kept as 1

array([ 6, 15])

axis and dimentions reasoning 

In [ ]:
# E1.1 — Predict output shape for each
x = np.ones((8, 10, 512))
# x.sum(axis=0).shape = ? (10,512)
# x.sum(axis=1).shape = ? (8,512)
# x.sum(axis=2).shape = ? (8,10)
# x.sum(axis=(0, 1)).shape = ? (512,)
# x.sum(axis=-1).shape = ? (8,10)
# x.max(axis=1).shape = ? (8,512) (note: np.max vs torch.max differ!)

In [ ]:
# E1.2 — Predict shapes
x = np.ones((32, 8, 128, 128))
# x.mean(axis=-1).shape = ? (32,8,128)
# x.mean(axis=-1, keepdims=True).shape = ? (32,8,128,1)
# x.sum(axis=(2, 3)).shape = ? (32,8)

In [ ]:
# E1.3 — Which axis to reduce?
# Given scores of shape (batch, heads, seq_len, seq_len) = (32, 8, 128, 128)
# To get attention weights, you softmax over the last dim (keys).
# What axis do you pass to softmax? Answer: axis=-1

In [27]:
# E1.4 — Normalize each feature across the batch
x = np.random.randn(100, 5)  # 100 samples, 5 features
# Write code to compute:
#   mean per feature (shape should be (5,) or (1,5))
#   std per feature
#   z-scored x (each feature has mean≈0, std≈1)
x_mean = x.mean(axis=0, keepdims=True)
x_std = x.std(axis=0, keepdims=True)
z = (x-x_mean)/x_std


In [35]:
# E1.5 — Real scenario: layer normalization
x = np.random.randn(2, 3, 4)  # (batch, seq, features)
# LayerNorm normalizes across the LAST dimension (features).
# Compute mean and std across dim=-1 with keepdims, then normalize.


def LayerNormed(x):
    x_mean = x.mean(axis=-1, keepdims=True)
    x_std = x.std(axis=-1, keepdims=True)
    return (x - x_mean) / x_std
LayerNormed(x)

array([[[-0.92752813,  1.67586728, -0.53409877, -0.21424038],
        [ 0.1666798 , -0.47444216, -1.20622242,  1.51398479],
        [ 1.1216089 ,  0.10488866,  0.38144808, -1.60794565]],

       [[ 1.31669827, -1.21841919, -0.67240953,  0.57413045],
        [-0.97236842, -0.4591536 , -0.23792919,  1.66945121],
        [ 0.60292039,  0.32046332, -1.70818123,  0.78479752]]])

In [ ]:
# E1.6 — argmax reasoning
x = np.array([[0.1, 0.7, 0.2],
              [0.3, 0.9, 0.4],
              [0.9, 0.05, 0.05]])
# x.argmax(axis=0) = ?  shape -> (3,) [2,1,1]
# x.argmax(axis=1) = ?  shape -> (3,) [1,1,0]

In [ ]:
# E2.1 — Implement ReLU without any loops or if statements
def relu(x):
    np.maximum(x,0)

In [43]:

# E2.2 — Implement softmax along axis=-1 (no loops)
# softmax(x)_i = exp(x_i) / sum(exp(x_j))
# Hint: use keepdims
def softmax(x, axis=-1):
    x_exp = np.exp(x)
    return x_exp / x_exp.sum(axis=axis, keepdims=True)

In [44]:
# E2.3 — Implement cross-entropy loss (no loops)
# L = -sum(y_true * log(y_pred)) / N
# y_true: (N, C) one-hot, y_pred: (N, C) probabilities
def cross_entropy(y_true, y_pred):
    N = y_true.shape[0]
    return -(y_true * np.log(np.clip(y_pred, 1e-9, 1))).sum() / N

In [45]:
# E2.4 — Predict the output
a = np.array([[1, 2], [3, 4]])
b = np.array([[10, 20], [30, 40]])
# a * b = ? (2,2)
# a ** b = ?  (element-wise power) (2,2)
# np.maximum(a, 3) = ? (2,2)


In [46]:

# E2.5 — GELU activation (approximate version)
# GELU(x) ≈ 0.5 * x * (1 + tanh(sqrt(2/π) * (x + 0.044715 * x^3)))
# Implement without loops:
def gelu(x):
    return 0.5 * x * (1 + np.tanh(np.sqrt(2 / np.pi) * (x + 0.044715 * x**3)))

In [49]:
# E2.6 — Given logits of shape (batch, num_classes) = (4, 5):
logits = np.random.randn(4, 5)
# Compute softmax probabilities (should sum to 1 along axis=1)
# Verify: probs.sum(axis=1) should be [1, 1, 1, 1]
probs = softmax(logits, axis=1)
probs.sum(axis=1)

array([1., 1., 1., 1.])